SELECT
    AG.NUAAG,
    AG.ATIVO AS STATUS_ACAO,
    AG.EXPGATILHO,
    AG.ACAO,
    AG.DESCRICAO,
    ROUND(SUM(TCM.TEMPOTOTAL) / NULLIF(SUM(TCM.QTDCOLETA), 0) / 1000.0, 2) AS TEMPO_MEDIO_SEGUNDOS,
    MAX(TCM.DHEXECUCAO) AS ULTIMA_EXECUCAO,
    SUM(TCM.QTDERROS) AS TOTAL_ERROS,
    CASE
        WHEN SUM(TCM.TEMPOTOTAL) / NULLIF(SUM(TCM.QTDCOLETA), 0) / 1000.0 > 5
            THEN 'alerta'
        ELSE 'ok'
    END AS STATUS
FROM TSITCM TCM
CROSS APPLY (
    SELECT
        CASE
            WHEN CHARINDEX('|', TCM.IDTIPO) > 0
                THEN LEFT(TCM.IDTIPO, CHARINDEX('|', TCM.IDTIPO) - 1)
            ELSE TCM.IDTIPO
        END AS ID_EXTRAIDO
) X
INNER JOIN TSIAAG AG
    ON AG.NUAAG = TRY_CONVERT(INT, X.ID_EXTRAIDO)
   AND AG.ATIVO = 'S'
WHERE TCM.TIPO = 'ACAO_AGEN'
  AND X.ID_EXTRAIDO IS NOT NULL
  AND LEN(X.ID_EXTRAIDO) > 0
  AND X.ID_EXTRAIDO NOT LIKE '%[^0-9]%'
GROUP BY AG.NUAAG, AG.ATIVO, AG.EXPGATILHO, AG.ACAO, AG.DESCRICAO
ORDER BY TEMPO_MEDIO_SEGUNDOS DESC

