SELECT
    JOB.MEDIAEXEC / 1000 AS MEDIA_DE_EXECUCAO,
    JOB.DESCRICAO         AS DESCRICAO_JOB,
    AG.EXPGATILHO,
    AG.NUAAG,
    AG.ACAO,
    CASE WHEN JOB.MEDIAEXEC / 1000 > 5 THEN 'alerta' ELSE 'ok' END AS STATUS
FROM TSIEJO JOB
INNER JOIN TSIAAG AG
    ON AG.NUAAG = TO_NUMBER(JOB.ID)
WHERE REGEXP_LIKE(JOB.ID, '^[0-9]+$')
ORDER BY MEDIA_DE_EXECUCAO DESC
