SELECT
    AG.NUAAG,
    AG.ATIVO AS STATUS_ACAO,
    AG.EXPGATILHO,
    AG.ACAO,
   -- MAX(TCM.DESCRICAO) AS DESCRICAO_JOB,
   AG.DESCRICAO,
    ROUND(SUM(TCM.TEMPOTOTAL) / NULLIF(SUM(TCM.QTDCOLETA), 0) / 1000, 2) AS TEMPO_MEDIO_SEGUNDOS,
    MAX(TCM.DHEXECUCAO) AS ULTIMA_EXECUCAO,
    SUM(TCM.QTDERROS) AS TOTAL_ERROS,
    CASE
        WHEN SUM(TCM.TEMPOTOTAL) / NULLIF(SUM(TCM.QTDCOLETA), 0) / 1000 > 5
            THEN 'alerta'
        ELSE 'ok'
    END AS STATUS
FROM TSITCM TCM
INNER JOIN TSIAAG AG
    ON AG.NUAAG = TO_NUMBER(REGEXP_SUBSTR(TCM.IDTIPO, '^[^|]+'))
   AND AG.ATIVO = 'S'
WHERE TCM.TIPO = 'ACAO_AGEN'
  AND REGEXP_LIKE(REGEXP_SUBSTR(TCM.IDTIPO, '^[^|]+'), '^[0-9]+$')
GROUP BY AG.NUAAG , AG.ATIVO, AG.EXPGATILHO, AG.ACAO,  AG.DESCRICAO
ORDER BY TEMPO_MEDIO_SEGUNDOS DESC