SELECT
    IDENTIFICADOR AS TITULO,
    SUM(QTDLOGIN)  AS CONTAGEM,
    LISTAGG(CODUSU || ' (' || QTDLOGIN || ')', ', ')
        WITHIN GROUP (ORDER BY QTDLOGIN DESC) AS DETALHE,
    CASE WHEN SUM(QTDLOGIN) > 5000 THEN 'alerta' ELSE 'ok' END AS STATUS
FROM (
    SELECT IDENTIFICADOR, CODUSU, SUM(QTDLOGIN) AS QTDLOGIN
    FROM TSIMAP
    WHERE ULTIMOLOGIN > SYSDATE - 30
    GROUP BY IDENTIFICADOR, CODUSU
)
GROUP BY IDENTIFICADOR
ORDER BY CONTAGEM DESC
