SELECT
    IDENTIFICADOR AS TITULO,
    SUM(QTDLOGIN) AS CONTAGEM,
    STRING_AGG(
        CAST(CODUSU AS VARCHAR(20)) + ' (' + CAST(QTDLOGIN AS VARCHAR(20)) + ')',
        ', '
    ) AS DETALHE,
    CASE
        WHEN SUM(QTDLOGIN) > 5000 THEN 'alerta'
        ELSE 'ok'
    END AS STATUS
FROM (
    SELECT
        IDENTIFICADOR,
        CODUSU,
        SUM(QTDLOGIN) AS QTDLOGIN
    FROM TSIMAP
    WHERE ULTIMOLOGIN > DATEADD(DAY, -30, GETDATE())
    GROUP BY
        IDENTIFICADOR,
        CODUSU
) AS X
GROUP BY
    IDENTIFICADOR
ORDER BY
    CONTAGEM DESC