WITH LOGINS_API AS (
    SELECT IDENTIFICADOR, CODUSU, SUM(QTDLOGIN) AS QTDLOGIN
    FROM TSIMAP
    WHERE ULTIMOLOGIN > SYSDATE - 30
    GROUP BY IDENTIFICADOR, CODUSU
),
DIAS_ATIVOS AS (
    -- dias distintos com pelo menos 1 login, considerando todos os
    -- usuários (CODUSU) que operam sob cada IDENTIFICADOR
    SELECT LA.IDENTIFICADOR, COUNT(DISTINCT TRUNC(LG.LOGIN)) AS QTD_DIAS
    FROM LOGINS_API LA
    JOIN TSIRLG LG ON LG.CODUSU = LA.CODUSU
    WHERE LG.LOGIN > SYSDATE - 30
    GROUP BY LA.IDENTIFICADOR
)
SELECT
    LA.IDENTIFICADOR AS TITULO,
    SUM(LA.QTDLOGIN) AS CONTAGEM,
    'média: ' || ROUND(SUM(LA.QTDLOGIN) / NULLIF(MAX(DA.QTD_DIAS), 0), 1) ||
        ' logins/dia (' || NVL(MAX(DA.QTD_DIAS), 0) || ' dias ativos) · ' ||
        LISTAGG(LA.CODUSU || ' (' || LA.QTDLOGIN || ')', ', ')
            WITHIN GROUP (ORDER BY LA.QTDLOGIN DESC) AS DETALHE,
    CASE WHEN SUM(LA.QTDLOGIN) > 5000 THEN 'alerta' ELSE 'ok' END AS STATUS
FROM LOGINS_API LA
LEFT JOIN DIAS_ATIVOS DA ON DA.IDENTIFICADOR = LA.IDENTIFICADOR
GROUP BY LA.IDENTIFICADOR
ORDER BY CONTAGEM DESC