SELECT
    JOB.DESCRICAO           AS DESCRICAO_JOB,
    JOB.STATUSEXEC,
    JOB.QTDFALHAS,
    SUBSTRING(JOB.MSGERRO, 1, 200) AS MSGERRO,
    JOB.TEMPOULIMAEXEC      AS ULTIMA_EXECUCAO,
    AG.EXPGATILHO,
    AG.ACAO,
    CASE WHEN JOB.QTDFALHAS > 0 THEN 'alerta' ELSE 'ok' END AS STATUS
FROM TSIEJO JOB
INNER JOIN TSIAAG AG
    ON AG.NUAAG = CONVERT(INT, JOB.ID)
WHERE JOB.ID IS NOT NULL
  AND LEN(JOB.ID) > 0
  AND JOB.ID NOT LIKE '%[^0-9]%'
  AND JOB.ATIVO = 'S'
ORDER BY JOB.QTDFALHAS DESC